#-- Zsh Environment Variables
#-- symlink: $HOME/.zshenv



#-------------------------------------------------------------------------------
#-- XDG Base Directory

# for dotfiles
export XDG_CONFIG_HOME="$HOME/.config"

# for specific data
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"

# for specific state
export XDG_STATE_HOME="$XDG_CONFIG_HOME/local/state"

# for cached files
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"



#-------------------------------------------------------------------------------
#-- Editors

export EDITOR="nvim"
export VISUAL="nvim"



#-------------------------------------------------------------------------------
#-- Zsh

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# history filepath
export HISTFILE="$ZDOTDIR/.zhistory"
# maximum events for internal history
export HISTSIZE=10000
# maximum events in history file
export SAVEHIST=10000



#-------------------------------------------------------------------------------
#-- Workspace Directory

# all projects go in $WORKSPACE directory

export WORKSPACE="$HOME/workspace"



#-------------------------------------------------------------------------------
#-- Dotfiles Repository

export DOTFILES="$HOME/dotfiles"



#-------------------------------------------------------------------------------
#-- Use ripgrep With fzf

export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"



#-------------------------------------------------------------------------------
#-- Node Version Manager
export NVM_DIR="$XDG_CONFIG_HOME/nvm"



#-------------------------------------------------------------------------------
#-- Homebrew Path (macos only)

if [[ $(uname) == "Darwin" ]]; then
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
fi



#-------------------------------------------------------------------------------
#-- Starship Prompt

export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
